#let pre_cite(..args, prefix: none) = {
  if prefix == none {
    cite(..args)
  } else {
    show "(": [(#prefix ]
    cite(..args)
  }
}

After repeated cost-overruns, in 2023, then prime minister of the United Kingdom, Rishi Sunak announced that the country's high speed rail project High Speed 2 (HS2) would be scaled down considerably, claiming that £36 billion in funds would be redirected to other transport projects @Sunak2023.
It is not uncommon for large infrastructure to run over-budget @Flyvbjerg2003, but, arguably -- though hard data are difficult to come by -- this was a rare occurrence of a large-scale infrastructure project being abandoned @Cornelio2021, despite funds having been appropriated with cross-party support @Topham2023 and construction having already begun on some parts of the project.
In addition to HS2, a number of large-scale infrastructure projects in western developed democracies -- sticking with rail projects Stuttgart 21 in Germany and California high-speed rail in the US come to mind -- have become somewhat notorious for their cost-overruns and construction delays, but, for now, HS2 remains an exception for funds being removed from the project.
So-called _megaprojects_, such as these, "are increasingly used as the preferred delivery model for goods and services across a range of businesses and sectors", at the same time they are considered "inherently risky due to long planning horizons and complex interfaces" @Flyvbjerg2014[pp. 6, 9].
Considering this, from a traditional economic point of view, in the presence of cost-overruns and higher return alternatives, project cancellation should then be the norm, as every additional pound to be spent should be evaluated on its marginal return alone.
Instead of cutting their losses, however, decision-makers, here politicians, will often _escalate their commitment_ @staw-1976 --- megaprojects continue to be funded, even if they might not have been funded in the first place, if the final costs and construction time had been known to be the actual costs in the initial decision scenario.
Now, there is a breadth of research on cognitive and decision biases that lead to suboptimal decision-making, which is, of course, not exclusively observed among politicians who need to decide whether to continue directing funding towards a megaproject.
As individuals, elite decision-makers are, in principle, liable to exhibiting choice anomalies like escalation of commitment @sleesman-2012. At the same time, as #cite(<sheffer-2017>, form: "prose", supplement: none), for instance, point out, elites appear to differ systematically from the general population #pre_cite(<Best2011>, prefix:"see e.g.")@Dietrich2012 and they operate in a idiosyncratic decision-environment, that impacts on how cognitive biases interact with elites' decision-making #pre_cite(<Miler2009>, prefix: "see e.g.").
To wit, they find evidence that elected politicians are overall _more prone_ to escalation of commitment that the general population.
The idiosyncrasy #pre_cite(<sheffer-2017>, form: "author", supplement: none) refer to relates to the mental shortcuts democratically elected political elites may be uniquely incentivized to take in the face of public opinion and retrospective voting #pre_cite(<weaver-1986>, prefix: "i.e. blame avoidance, see"), the introductory example illustrates that the _content_ of what politicians need to make decisions on is also idiosyncratic: In political elites' minds, large public infrastructure projects are not necessarily expected to pay for themselves directly, in the same way, say, a private real estate development would be expected to recoup its initial capital investment as quickly as possible, rather increased economic activity, emissions savings, etc. are major components of a megaproject's return on investment.
Similarly, political elites may have different outlooks on the financial return of other kinds of government programs, such as welfare spending: On the one hand, for contributory programs, e.g. many government pensions programs, it is easier to evaluate if they are solvent -- does more come in in contributions than goes out in obligations?
On the other hand, despite the fact that, due to their aging populations, the pension systems of many developed democracies, especially those that operate on a pay-as-you-go basis, increasingly face problems with long-term financial sustainability and even insolvency @cbo-2024, contrary to the rationalist expectation, pension reform is rare and the general trajectory of relative government pension spending has been invariably upwards for the last four decades (see @app1 in the appendix).
From an escalation of commitment point of view, it is, again, questionable if politicians internalize and conceptualize social spending in terms of naked return on investment.

Of course, there is a plethora of plausible theoretical explanations outside of decision biases for why some policy or funding appropriation might be maintained or expanded, even in the face of suboptimal outcomes, e.g. path dependency #pre_cite(<pierson-2000>, prefix: "e.g."), or different political economy approaches #pre_cite(<guardiancich-2020>, prefix: [for pensions e.g.], supplement: none), but insofar as politicians are affected by decision anomalies in their decision behavior, it is worthwhile to more closely examine how those who directly decide on the distribution of rights and scarce goods in a political community come to maintain a course of action that may be less than optimal for that community.
// -- still, assuming politicians' voting behavior is affeected decision anomalies do impact their , the literature on escalation of commitment does not adequately address the idiosyncrasies of elected politicians' decision environment.
Escalation of commitment is readily studied in political science, but, it is more often, or even predominantly, studied through an organizational behavior lens #pre_cite(<sleesman-2012>, prefix: "see"), as a result the concept is usually operationalized in terms of managerial performance and investment decisions in a commercial context.
// This paper is interested in politicians' decision making, who effectuate political outcomes via decisions on laws, general regulations and how to spend public funds
One prominent instance of research on escalation of commitment in an exclusively political context has been regarding international relations, specifically armed conflict, e.g. why a conflict is escalated despite bad news from the battlefield #pre_cite(<staw-1976>, prefix: [the Vietnam war being the go-to example, see e.g.], supplement: none), or sunk costs as a tool of international politics #pre_cite(<fearon-1997>, prefix: [see e.g.], supplement: none).
Doubtless, international politics is a special decision environment, in most cases idiosyncratic to politicians, however, it is also usually the sole domain of the executive, usually a small number of high-ranking politicians such as elected officials like heads of state or government, and a mix of political appointees (e.g. a foreign minister) and career diplomats and national security officials (e.g. intelligence officers), the latter of whom aren't necessarily politicians.
This paper is only interested in elected politicians' behavior, more specifically the population of interest for this paper is politicians who are democratically elected to a legislative body on the national level.
// who achieve political outcomes by making decisions on how to spend public funds.
Because much of the literature on escalation of commitment concerns itself with investment decision environments, this paper will be limited to politicians' decisions regarding the spending of public funds, as compared to, say, other kinds of laws and general regulations.

Even studies that set out to more narrowly investigate escalation of funding among elected members of a legislative body, understandably, draw on the established catalogue of, almost standard, survey instruments from the organizational behavior literature #pre_cite(<sheffer-2017>, prefix: "e.g.")@linde-2016.
Proceeding under the reasonable assumption, then, that elected politicians, more often than not, find themselves in non-standard decision-environments, at least compared to the most common conceptualizations in the organizational behavior literature, I ask, _how do the peculiarities of budget appropriation in a legislative body affect escalation of commitment among politicians?_
For the purpose of this paper, I will adopt the two different kinds of decision referred to throughout the introductory example, funding for megaprojects and funding for pension programs, because they capture the kind of difference in decision content that is particular to the context of elected politicians.

In the sections that follow, I will first establish a baseline economic approach to escalation of commitment among politicians, which will server as springboard for further discussion of more interesting empirical findings and other theoretical approaches.
I will argue that prospect theory @kahneman-1979
Finally I develop an empirical strategy to test my hypotheses, proposing a new survey instrument that is more tailored to the research question.

My contribution is to develop questin that ask specifgically abouzt scenarion relevant to politicians and if theres a difference there! Not just if politican sexhibit the behavior itself in question that re not ralted to theirjobs!!! my orginal plan!!

Talk about @linde-2016


// Even when #cite(<sheffer-2017>, form: "prose") explicitly set out to study elected elites' behavior, they ask members of different national legislatures whether they would invest an additional \$100 million in a small business loan program, on which \$500 million have already been spent. Respondent are further informed that the program will not cover its cost, unless the additional money is spent (including the additional funds).

// a sensitive political issue #pre_cite(<neely-1996>, prefix: "here Social Security in the U.S.,")#pre_cite(<leali-2023>, prefix: "see e.g. protests in France,"), at times having been given the moniker _political "third rail"_ , meaning an issue that can't be touched, but beyond electoral pressure, it is again

// While attempts at reform continue @Martinez2024, again in contradiction to the the rationalist expectation, the general relative trajectory of government pension spending has been invariably upwards for the last four decades (see @app1 in the appendix).

// These and other, are often cited as instances of _escalation of commitment_, i.e. continuing to fund suboptimal or failed policies, so that funds that have already been invested do not go to _waste_.

// On the demand side, the question of policy stability in the face of more optimal alternatives, especially regarding welfare policy, is well explored. On the supply side, there is the considerable body of research on partisan differences, however there hasn't been

// #cite(<sheffer-2017>, form: "prose", supplement: none), for instance, find in a series of survey experiments that politicians tend to exhibit several decision biases at similar rates as the general population. As regards the sunk-cost fallacy and escalation of commitment, however, politicians are actually more likely to exhibit biased thinking than the general population.

// #cite(<sheffer-2017>, form: "prose") ask members of different national legislatures whether they would invest an additional \$100 million in a small business loan program, on which \$500 million have already been spent. Respondent are further informed that the program will not cover its cost, unless the additional money is spent (including the additional funds). However, for large infrastructure projects, the idea of financial solvency does not straightforwardly apply, e.g. a high-speed rail project is not expected to pay for itself directly, but diffusely via increased economic activity, emissions savings, etc. This raises the possibility that politicians may evaluate infrastructure programs run over budget differently from e.g. social security programs that run a deficit (like many pension systems do). I therefore ask:

// _How does policy domain affect escalation of commitment among politicians?_
